function gvjs_oZ(a){gvjs_O.call(this,a);this.qe=new gvjs_7m(this,this.container);this.Wu="google.visualization.MotionChart-"+gvjs_Rla++;gvjs_pZ[this.Wu]=this;this.JT=this.Wu+"_swf";a.id||(a.id=this.Wu);this.Lsa=gvjs_tl()}gvjs_r(gvjs_oZ,gvjs_O);var gvjs_qZ=gvjs_MP("flash_subdir",gvjs_jd,"1");gvjs_qZ.Oh.subdir="en";gvjs_qZ.Oh.filename="tlz-gviz.swf";var gvjs_Sla=gvjs_Cf(gvjs_KP(gvjs_qZ));gvjs_oZ.prototype.Wu=null;gvjs_oZ.prototype.JT=null;gvjs_oZ.prototype.kL=null;var gvjs_Rla=0,gvjs_pZ={};gvjs_=gvjs_oZ.prototype;
gvjs_.pn=!0;gvjs_.pda=-1;gvjs_.jN=!1;gvjs_.n0="";gvjs_.W=null;gvjs_.hg=function(a,b,c){a=c||{};this.W=b;c=this.container;this.qe.removeAll();if(b){try{this.VL(b)}catch(e){this.qe.pe(e.message);return}this.jN=!1;null==this.kL&&(this.kL=gvjs_Sla);var d=gvjs_fy(a,1);this.pn||d!=this.pda?(this.pn=!1,this.pda=d,this.f2(c,a),this.n0=gvjs_rZ(b)):(b=gvjs_rZ(b),b==this.n0?this.vf().dataChanged():(this.vf().metricTablesChanged(),this.n0=b))}else this.qe.pe("Data table is null")};
function gvjs_rZ(a){for(var b="",c=a.Z(),d=0;d<c;d++)b+=a.Y(d)+":"+a.Ca(d)+",";return b}gvjs_.vf=function(){return null!=this.JT?gvjs_sl().getElementById(this.JT):null};gvjs_.Era=function(a){if(null!=this.kL)throw Error("Swf url already initialzed");this.kL=a};gvjs_.getState=function(){return this.jN?gvjs_Og(this.vf().getState()):null};
gvjs_.VL=function(a){if(3>a.Z())throw Error("There should be at least three columns in the data.");var b;if(!(b=a.Y(0)!=gvjs_j)){b=a.Y(1);var c=!1,d=a.getValue(0,1);switch(b){case gvjs_f:c=0<=d&&Math.floor(d)==d;break;case gvjs_j:c=/^[0-9]{4}Q[1-4]{1}$/.test(d)||/^[0-9]{4}W[0-9]{2}$/.test(d)||/^[0-9]{4}-((0[1-9])|(1[0-2]))$/.test(d);break;case gvjs_Pb:case gvjs_Qb:c=!0}b=!c}if(b)throw Error("First and second columns must be entity and time.");c=b=0;d=a.Z();for(var e=2;e<d;e++){if(a.Y(e)!=gvjs_f&&
a.Y(e)!=gvjs_j)throw Error("All data columns must be string or numbers.");a.Y(e)==gvjs_f?b++:c++}if(1>b)throw Error("There must be at least one numeric column.");};
gvjs_.f2=function(a,b){var c=this.kL.replace("/en/","/"+this.Lsa+"/"),d=parseInt(b.width,10)||500,e=parseInt(b.height,10)||300,f=b.state;f=typeof f===gvjs_j?f:"";var g=decodeURIComponent(f);f=(/^\s*$/.test(g)?0:/^[\],:{}\s\u2028\u2029]*$/.test(g.replace(/\\["\\\/bfnrtu]/g,"@").replace(/(?:"[^"\\\n\r\u2028\u2029\x00-\x08\x0a-\x1f]*"|true|false|null|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?)[\s\u2028\u2029]*(?=:|,|]|}|$)/g,"]").replace(/(?:^|:|,)(?:[\s\u2028\u2029]*\[)+/g,"")))?encodeURIComponent(f):"";f={state:f,
chartId:this.Wu||"",js:"blocking"};g={id:this.JT};gvjs_sZ("showSelectList","opt_.featureConfig_selectListComponent",b,f);gvjs_sZ("showSidePanel","opt_.featureConfig_sidePanel",b,f);gvjs_sZ("showXMetricPicker","opt_.featureConfig_xMetricPicker",b,f);gvjs_sZ("showYMetricPicker","opt_.featureConfig_yMetricPicker",b,f);gvjs_sZ("showXScalePicker","opt_.featureConfig_xScalePicker",b,f);gvjs_sZ("showYScalePicker","opt_.featureConfig_yScalePicker",b,f);gvjs_sZ("showHeader","opt_.featureConfig_chartHeader",
b,f);gvjs_sZ(gvjs_Tw,"opt_.featureConfig_chartButtons",b,f);gvjs_sZ("showAdvancedPanel","opt_.featureConfig_advancedPanel",b,f);gvjs_sZ("showSliderTimeDisplay","opt_.featureConfig_sliderTimeDisplay",b,f);gvjs_uh(a);b=gvjs_fh(a).createElement(gvjs_Sb);var h=a.id+"_flashElement";b.id=h;a.appendChild(b);new gvjs_LP.b9(c,h,d,e,"9.0.0",!1,f,{scale:gvjs_ju,allowScriptAccess:"always",wmode:"opaque",bgcolor:gvjs_Mr},g)};
function gvjs_tZ(a){gvjs_uZ(a);a=gvjs_pZ[a];for(var b=[{name:a.W.Ca(0),id:"dim0"}],c=[],d=a.W.Z(),e=2;e<d;e++)c.push({id:e,name:a.W.Ca(e),type:a.W.Y(e)==gvjs_f?"continuous":"discrete",hasTime:!0});return gvjs_Og({dimensions:b,metrics:c})}
function gvjs_vZ(a,b){gvjs_uZ(a);a=gvjs_pZ[a];var c=a.W.Y(1),d=[],e=[],f=[];f.push(d);f.push(e);for(var g=new gvjs_B(2,a.W.Z()-1),h=0;h<b.length;h++){if(!gvjs_Xh(g,Number(b[h])))throw Error("Column index out of range: "+b[h]);f.push([])}g=a.W.ca();for(var k=0;k<g;k++)for(h=(a.W.Ha(k,0)+"").replace(/[\\"']/g,""),d.push(h),e.push(gvjs_Tla(a.W.getValue(k,1),c)),h=0;h<b.length;h++)f[h+2].push(a.W.getValue(k,Number(b[h])));return gvjs_Og(f)}
function gvjs_wZ(a){gvjs_uZ(a);a=gvjs_pZ[a];gvjs_N(a,gvjs_Kd,null);a.jN||(a.jN=!0,gvjs_N(a,gvjs_g,null))}function gvjs_uZ(a){if(null==gvjs_pZ[a])throw Error("No chart with id "+a+" exists");}
function gvjs_Tla(a,b){if(b==gvjs_f)a=String(a);else if(b==gvjs_j&&(-1<a.indexOf("Q")||-1<a.indexOf("W")||4==a.indexOf("-")))a=String(a);else if(b==gvjs_Pb||b==gvjs_Qb){b=[];b.push(String(a.getFullYear()));var c=String(a.getMonth()+1);1==c.length&&(c="0"+c);b.push(c);a=String(a.getDate());1==a.length&&(a="0"+a);b.push(a);a=b.join("-")}else a=null;return a}function gvjs_sZ(a,b,c,d){a=c[a];null!=a&&(d[b]=!!a)};gvjs_o(gvjs_Hc,gvjs_oZ,void 0);gvjs_oZ.prototype.draw=gvjs_oZ.prototype.draw;gvjs_oZ.prototype.getState=gvjs_oZ.prototype.getState;gvjs_oZ.prototype.getChart=gvjs_oZ.prototype.vf;gvjs_oZ.prototype.initSwfUrl=gvjs_oZ.prototype.Era;gvjs_o("google.visualization.getMetadata",gvjs_tZ,void 0);gvjs_o("google.visualization.getMetricValues",gvjs_vZ,void 0);gvjs_o("google.visualization.updateExternalState",gvjs_wZ,void 0);gvjs_o("getMetadata",gvjs_tZ,void 0);gvjs_o("getMetricValues",gvjs_vZ,void 0);
gvjs_o("updateExternalState",gvjs_wZ,void 0);
