/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
var gvjs_1S="#00000000",gvjs_2S="__ImageChartId__",gvjs_3S="error: cannot draw chart",gvjs_4S="google-visualization-sparkline-default",gvjs_5S="google-visualization-sparkline-selected";function gvjs_6S(a){if(a instanceof gvjs_og)return a;a=gvjs_sg(a);var b=gvjs_qg(a).replace(/(\r\n|\r|\n)/g,gvjs_na);return gvjs_tg(b,a.ht())}gvjs_hC.prototype.c3=gvjs_W(8,function(a){gvjs_lC(this,gvjs_6S(a))});
function gvjs_7S(a,b,c,d){if(null!=a)for(a=a.firstChild;a;){if(b(a)&&(c.push(a),d)||gvjs_7S(a,b,c,d))return!0;a=a.nextSibling}return!1}function gvjs_8S(a){return Array.prototype.join.call(arguments,"")}function gvjs_kja(a,b){var c=[];return gvjs_7S(a,b,c,!0)?c[0]:void 0}function gvjs_9S(a){var b=gvjs_lja,c=a&&a.colors;c&&0!=c.length||(c=(a=a&&a.color)?[a]:b);return c}
function gvjs_$S(a,b,c,d,e){gvjs_OB.call(this,d);this.Me=new gvjs_xl(e||"//chart.googleapis.com/chart");this.vO="";this.ky=[];this.N2=[];this.fT=[];this.$r=[];this.ysa=[];this.Fva=[];this.NJ=[];this.F0={};this.xta={};this.jR={};this.yta={};this.Pw(a);this.Jg(b,c);this.Ya=gvjs_aT(this)?0:Infinity}gvjs_r(gvjs_$S,gvjs_OB);gvjs_=gvjs_$S.prototype;gvjs_.Tga=2048;gvjs_.Qoa=0;gvjs_.Roa=0;gvjs_.Cb=-Infinity;gvjs_.Ij=null;gvjs_.Vxa=13.5;gvjs_.v4="333333";gvjs_.S0=null;
gvjs_.K=function(){var a=this.Xb();this.H=this.xa().K("IMG",{src:gvjs_bT(this),"class":"aAAaGVIZSENTINELaAAa-serverchart-image",width:a[0],height:a[1]})};gvjs_.Jf=function(a){var b=gvjs_bT(this).toString();if(!(b instanceof gvjs_Vf)){var c=/^data:image\//i.test(b);b=gvjs_hA(b,c)}a.src=gvjs_Yf(b);this.H=a};gvjs_.setUri=function(a){this.Me=a};
function gvjs_bT(a){if(""!=a.vO)var b=gvjs_cT(a,a.vO);else(b=gvjs_cT(a,"e"))||(b=gvjs_cT(a,"s"));b||a.dispatchEvent(new gvjs_dT(a.Me.toString()));return a.Me}function gvjs_mja(a,b){var c=[];gvjs_s(b,function(d){d.area=d.area||"bg";d.effect=d.effect||"s";c.push([d.area,d.effect,d.color].join())});c=c.join("|");a.Od("chf",c)}gvjs_.Pw=function(a){this.Me.Od("cht",a)};gvjs_.getType=function(){return this.Me.ng.get("cht")};gvjs_.Jg=function(a,b){a=[a||300,b||150].join("x");this.Me.Od("chs",a)};
gvjs_.Xb=function(){return this.Me.ng.get("chs").split("x")};gvjs_.hT=function(a){this.Ya=a};gvjs_.gT=function(a){this.Cb=a};function gvjs_eT(a){a=a.getType();return"br"==a||"bhg"==a||"bhs"==a||"bvg"==a||"bvs"==a}function gvjs_aT(a){a=a.getType();return"p"==a||"p3"==a||"pc"==a}function gvjs_fT(a){a=a.getType();return"br"==a||"bhg"==a||"bhs"==a}gvjs_.isMap=function(){var a=this.getType();return"t"==a||"tuss"==a||"twoc"==a};function gvjs_gT(a){a=a.getType();return"br"==a||"bhs"==a||"bvs"==a}
gvjs_.Od=function(a,b){this.Me.Od(a,b)};gvjs_.removeParameter=function(a){this.Me.removeParameter(a)};gvjs_.setTitle=function(a){this.Ij=a;this.Me.Od("chtt",this.Ij.replace(/\n/g,"|"))};gvjs_.setTitleColor=function(a){this.v4=a;this.Me.Od("chts",this.v4+","+this.Vxa)};gvjs_.getTitleColor=function(){return this.v4};function gvjs_hT(a,b){a.NJ.push(b);a.Me.Od("chxt",a.NJ.join(","));return a.NJ.length-1}function gvjs_iT(a,b,c){a.F0[b]=c;b=gvjs_jT(a,a.F0,":|","|");a.Me.Od("chxl",b)}
function gvjs_kT(a,b,c,d){var e=Infinity;for(var f=0,g=b.length;f<g;++f){var h=b[f];null!=h&&h<e&&(e=h)}e<a.Ya&&(a.Ya=e);e=-Infinity;f=0;for(g=b.length;f<g;++f)h=b[f],null!=h&&h>e&&(e=h);e>a.Cb&&(a.Cb=e);if(void 0!==d){if(a.fT.length<a.ky.length)throw Error("Cannot start adding legends text after first element.");a.fT.push(d);a.Me.Od("chdl",a.fT.join("|"))}a.ky.push(b);a.N2.push(c);a.Me.Od("chco",a.N2.join(","))}gvjs_.getData=function(a){return void 0!==a?this.ky[a]:this.ky};
function gvjs_cT(a,b){for(var c=[],d=0,e=a.ky.length;d<e;++d){var f=c,g=d;var h=a;for(var k=a.ky[d],l=a.Ya,m=a.Cb,n=b,p=[],q=0,r=k.length;q<r;++q){var t=k[q];var u="e"==n;if(null===t||void 0===t||isNaN(t)||t<l||t>m)t=u?"__":"_";else if("t"==n)t=String(t);else{var v=.5;m>l&&(v=(t-l)/(m-l));t=u?"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789-.".charAt(Math.floor(v*gvjs_lT/64))+"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789-.".charAt(Math.floor(v*gvjs_lT%64)):"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789".charAt(Math.round(61*
v))}p.push(t)}h=p.join("t"==h.vO?",":"");f[g]=h}c=c.join("t"==b?"|":",");b=null==a.S0?gvjs_8S(b,":",c):gvjs_8S(b,a.S0,":",c);a.Me.Od("chd",b);return a.Me.toString().length<a.Tga}function gvjs_jT(a,b,c,d){var e=[],f=0;for(a=a.NJ.length;f<a;++f)b[f]&&e.push(f+c+b[f].join(d));return e.join("|")}var gvjs_lT=Math.pow(64,2)-1;
gvjs_$S.prototype.O=function(){gvjs_$S.o.O.call(this);delete this.$r;delete this.ysa;delete this.Fva;delete this.Qoa;delete this.Roa;delete this.N2;delete this.fT;delete this.ky;this.Me=null;delete this.Ya;delete this.Cb;this.Ij=null;delete this.NJ;delete this.F0;delete this.xta;delete this.jR;delete this.yta};function gvjs_dT(a){gvjs_Vl.call(this,"uritoolong");this.uri=a}gvjs_r(gvjs_dT,gvjs_Vl);function gvjs_mT(a,b){gvjs_O.call(this,b);this.w7=a;this.qe=new gvjs_7m(this,this.container)}gvjs_m(gvjs_mT,gvjs_O);gvjs_=gvjs_mT.prototype;gvjs_.pe=function(a){this.qe.pe(a)};function gvjs_nT(a){return 0<a.Z()&&a.Y(0)==gvjs_j?1:0}function gvjs_oT(a,b){gvjs_K(b,"load",a.gx.bind(a));gvjs_K(b,gvjs_Vb,a.pe.bind(a,gvjs_3S))}gvjs_.gx=function(){gvjs_N(this,gvjs_g,null)};gvjs_.mya=function(a){gvjs_N(this,"on"+a.type,a)};
function gvjs_nja(a){return gvjs_kja(a.container,function(b){return b.tagName?"map"===String(b.tagName).toLowerCase():!1})}function gvjs_pT(a){return"r"==a||"rs"==a}
function gvjs_oja(a,b,c,d){for(var e=Math.floor(1E5*Math.random());c.j(gvjs_2S+e);)e++;e=gvjs_2S+e;var f=c.K(gvjs_rs,{id:e,name:e});c.appendChild(a.container,f);b.useMap="#"+e;(new gvjs_Jl(d)).fetch({chof:"json"}).then(function(g){if(g.chartshape){var h=gvjs_nja(a);if(null==h)a.pe("Cannot create events map");else for(var k=g.chartshape.length-1;0<=k;k--){var l=c.createElement(gvjs_et);l.coords=g.chartshape[k].coords;l.shape=g.chartshape[k].type;for(var m=gvjs_qT.length,n=0;n<m;n++){var p=new gvjs_Vl(gvjs_qT[n],
l);p.type=gvjs_qT[n];p.region=g.chartshape[k].name;gvjs_K(l,gvjs_qT[n],a.mya.bind(a,p),!0)}h.appendChild(l)}}})}
gvjs_.hg=function(a,b,c){a=c||{};if(b&&this.container&&this.w7)if(c=this.IG(b,a)){b=gvjs_bT(c);if(!b||!b.tp){var d=(new gvjs_xl(gvjs_sl().location.href)).tp;"http"!=d&&"https"!=d&&gvjs_yl(b,"http")}if(b.toString().length>c.Tga){c=b.ng.get("chs");c=c.split("x");a=gvjs_rl().createElement(gvjs_Pa);a.width=c[0];a.height=c[1];a.frameBorder="0";a.scrolling="no";a.marginHeight="0";a.marginWidth="0";this.container.appendChild(a);c=a.contentDocument;c||(c=a.contentWindow.document);c.open();c.close();d=c;var e=
d.getElementsByTagName(gvjs_Cb)[0];c=d.createElement("form");e.appendChild(c);e=b.ng.kj();e=gvjs_$d(e);for(var f=e.next();!f.done;f=e.next()){f=f.value;var g=b.ng.get(f),h=d.createElement(gvjs_hv);h.type=gvjs_Cp;h.name=f;h.value=g;c.appendChild(h)}gvjs_Cl(b,null);b=b.toString();b=b instanceof gvjs_Vf?b:gvjs_hA(b);c.action=gvjs_Yf(b);c.method="POST";gvjs_oT(this,a);c.submit()}else c.V(this.container),d=c.j(),gvjs_oT(this,d),a.enableEvents&&(a=c.xa(),gvjs_oja(this,d,a,b))}else this.pe(gvjs_3S)};
gvjs_.IG=function(a,b){var c;b=b||{};var d=this.w7,e,f=!0;switch(d){case 2:var g="lc";break;case 1:f=b.showAxisLines;null==f&&(f=!0);g=f?"lc":"ls";break;case 3:g=b.is3D?"p3":"p";break;case 4:var h=b.isVertical;g=b.isStacked;null==g&&(g=!0);g=g?h?"bvs":"bhs":h?"bvg":"bhg";break;case 5:g=b.cht;break;default:return null}gvjs_uh(this.container);var k=b;var l="lr"==g||"lc"==g||"ls"==g;var m=this.container;h=(c=k&&k.isInternal)?void 0:1E3;var n=c?void 0:1E3;if("t"==g||"tuss"==g||"twoc"==g)h=440,n=220;h=
gvjs_ZA(m,k,0,h);k=l?gvjs__A(m,k,0,n,15):gvjs__A(m,k,0,n);c||(c=h*k,3E5<c&&(c=Math.sqrt(c/3E5),h/=c,k/=c));c=Math.floor(h);l=Math.floor(k);h=new gvjs_$S(g,c,l);b.addPadding&&(c=k=.19*c,l=m=.19*l,c=[c,k,l,m].join(),h.Me.Od("chma",c));if(c=!(b&&b.isInternal))k=h.Xb(),c=parseInt(k[0],10),k=parseInt(k[1],10),c=!(1E3<c||1E3<k?0:3E5>=c*k);if(c)throw Error("Assertion failed: invalid size.");(c=b.title)&&h.setTitle(c);k=b.singleColumnDisplay;var p=a.Z();l=a.ca();var q=0<p&&a.Y(0)!=gvjs_f;m=0;for(var r=q?
1:0;r<p;){if(a.Y(r)==gvjs_f){if(null==k||r==k)break;m++}r++}if(null!=k||3==d)var t=1;c=0;n=!1;for(e=r;e<p;e++)if(a.Y(e)==gvjs_f){if(t&&c==t)break;null==k&&a.Ca(e)&&!gvjs_aT(h)&&"s"!=g&&"lxy"!=g&&(n=!0);c++}var u=b.min,v=b.max;if(gvjs_aT(h))u=0,v=null;else if(gvjs_eT(h)){if(!u||gvjs_gT(h)&&1<c)u=0;if(gvjs_gT(h)&&1<c)for(p=0;p<l;p++){var w=0;e=r;for(t=0;t<c;e++)a.Y(e)==gvjs_f&&(w+=a.getValue(p,e),t++);if(!v||w>v)v=w}}(u||0===u)&&h.hT(u);(v||0===v)&&h.gT(v);t=b.showCategoryLabels;null==t&&(t=f);if(q&&
t){t=[];for(p=0;p<l;p++)t.push(a.Ha(p,0)||"");if(gvjs_aT(h))b.legend!=gvjs_e&&h.Od("chdl",t.join("|")),b.labels==gvjs_Yv&&(h.$r=t,h.Me.Od("chl",h.$r.join("|")));else if(gvjs_fT(h))t.reverse(),gvjs_hT(h,"y"),gvjs_iT(h,0,t);else if((e=gvjs_eT(h))||(e=h.getType(),e="lr"==e||"lc"==e||"ls"==e||"lxy"==e),e||gvjs_pT(g))gvjs_hT(h,"x"),gvjs_iT(h,0,t)}t="r";switch(b.legend){case gvjs_dd:t="l";break;case gvjs_px:t="t";break;case gvjs_wt:t="b";break;case gvjs_e:n=!1}h.Me.Od("chdlp",t);e=r;for(t=0;t<c;e++)if(a.Y(e)==
gvjs_f){r=[];q=n?a.Ca(e)||"":void 0;for(p=0;p<l;p++)r.push(a.getValue(p,e));p=gvjs_rT(null!=k?m:t,b);gvjs_kT(h,r,p,q);gvjs_aT(h)&&b.labels==gvjs_Xd&&(h.$r=r,h.Me.Od("chl",h.$r.join("|")));t++}if(gvjs_eT(h)||gvjs_pT(g)||"gom"==g||"lr"==g||"lc"==g||"ls"==g)t=b.showValueLabels,null==t&&(t=f),t&&(f="y",gvjs_fT(h)&&(f="x"),t=b.valueLabelsInterval,null==t&&gvjs_pT(g)&&null==b.chds&&(t=(h.Cb-h.Ya)/4),gvjs_sT(h,f,{interval:t}));gvjs_eT(h)&&h.Me.Od("chbh","a");g=b.firstHiddenColumn;null!=g&&(g-=gvjs_nT(a),
h.S0=g);if(2==d||b.fill){d=c;g=b;f=[];t=null==g.firstHiddenColumn?d:g.firstHiddenColumn;for(c=0;c<t;c++)k=gvjs_rT(c,g),k=["b",k,c,c+1==t?d:c+1,0],f.push(k.join(","));d=f.join("|");h.Me.Od("chm",d);d=[];g=h.Ya;d.push(g);d.push(g);gvjs_kT(h,d,"00000000",void 0)}this.vp(h,a,b);this.setBackgroundColor(h,b);return h};gvjs_.setBackgroundColor=function(a,b){b=b.backgroundColor;null!=b&&(b=b.replace("#",""),gvjs_mja(a,[{area:"bg",color:b}]))};
function gvjs_pja(a,b){if(gvjs_pT(a))return b.Z()-gvjs_nT(b);switch(a){case "p":case "pc":case "s":return b.ca();case "v":return 3;case "br":case "bhg":case "bhs":case "bvg":case "bvs":case "lc":return b.Z()-gvjs_nT(b);case "lxy":return(b.Z()-gvjs_nT(b))/2;default:return null}}
gvjs_.vp=function(a,b,c){if("lc"!=a.getType()){var d=c.singleColumnDisplay;if(null==d){c=gvjs_9S(c);b=gvjs_pja(a.getType(),b);b=null===b?c.length:b;d=[];for(var e=0;e<b;e++)d[e]=c[e%c.length];c=d=d.join(",").replace(/#/g,"");gvjs_bT(a).Od("chco",c)}else c=gvjs_rT(d,c),gvjs_bT(a).Od("chco",c)}};
function gvjs_sT(a,b,c){c=c||{};b=gvjs_hT(a,b);var d=null!=c.min?c.min:a.Ya,e=null!=c.max?c.max:a.Cb;isFinite(d)&&isFinite(e)?d==e?gvjs_iT(a,b,["",d,""]):(c=c.interval,a.jR[b]=[d,e],void 0!==c&&a.jR[b].push(c),c=gvjs_jT(a,a.jR,",",","),a.Me.Od("chxr",c)):(d=isFinite(d)?d:"",e=isFinite(e)?e:"",gvjs_iT(a,b,[d,e]))}
function gvjs_rT(a,b){var c=b.singleColumnDisplay;null!=c&&(a=c);c=(c=b.chco)&&typeof c==gvjs_j&&-1==c.indexOf("|")?c.split(","):gvjs_9S(b);a=c[a%c.length];"#"==a.charAt(0)&&(a=a.substring(1));return a}var gvjs_lja=["#3399CC","#80C65A","#FF0000","#FFCC33","#BBCCED","#3399CC","#990066",gvjs_Lr],gvjs_qT=[gvjs_1t,gvjs_pd,gvjs_od];function gvjs_tT(a){gvjs_mT.call(this,5,a);this.g8=null}gvjs_m(gvjs_tT,gvjs_mT);gvjs_tT.prototype.vp=function(a,b,c){null==c.colors&&"s"==a.getType()?a.removeParameter("chco"):gvjs_mT.prototype.vp.call(this,a,b,c)};
gvjs_tT.prototype.IG=function(a,b){if(!a||!this.getContainer())return null;var c=b;c=c?gvjs_w(c):{};b=c.cht;null==b&&(b="lc",c.cht=b);var d=c.chs;null!=d&&(d=d.split("x"),c.width=parseInt(d[0],10),c.height=parseInt(d[1],10));"gom"==b&&(null==c.min&&(c.min=0),null==c.max&&(c.max=100));b=c;c=gvjs_mT.prototype.IG.call(this,a,b);d=b;for(var e in d)if(!gvjs_qja[e]){var f=d[e];if(null!=f){var g=e;gvjs_bT(c).Od(g,f)}}e=b;b=c.getType();d=null==e.chxt;if(gvjs_pT(b))d&&0==gvjs_nT(a)&&(b=gvjs_hT(c,"x"),gvjs_iT(c,
b,"0 45 90 135 180 225 270 315".split(" ")));else switch(b){case "t":b=a.Z();(d=2==b)||this.pe("The DataTable has an unexpected number of columns.  Expected: 2, actual: "+b);if(d&&gvjs_uT(this,a,0,gvjs_j)&&gvjs_uT(this,a,1,gvjs_f)){b="";for(d=0;d<a.ca();d++)b+=a.getValue(d,0);gvjs_bT(c).Od("chld",b)}break;case "s":case "lxy":if(d){g=e.chds;g=typeof g===gvjs_j?g.split(","):[];b=g[0];d=g[1];f=g[2];g=g[3];f=void 0!==f?f:b;g=void 0!==g?g:d;var h=e.valueLabelsInterval;gvjs_sT(c,"x",{min:b,max:d,interval:h});
gvjs_sT(c,"y",{min:f,max:g,interval:h})}}(b=null!=e.chds)||(b=e.chm,b=typeof b===gvjs_j&&"N"==b.charAt(0));b&&(c.vO="t");b=e.annotationColumns;if(null!=b&&!gvjs_Me(b)){d=gvjs_nT(a);e=[];for(f=0;f<b.length;f++){g=b[f];h=g.column;var k=g.positionColumn||d;k-=d;var l=g.color;l=l||"000000";"#"==l.charAt(0)&&(l=l.substring(1));var m={low:-1,medium:0,high:1}[g.priority]||0,n="t";"flag"==g.type&&(n="f");for(var p=0;p<a.ca();p++){var q=a.getValue(p,h);if(null!=q){var r=[];r.push(n+q);r.push(l);r.push(k);
r.push(p);r.push(g.size);r.push(m);r=r.join(",");e.push(r)}}}a=c.Me.ng.get("chm");null!=a&&0<a.length&&e.push(a);0<e.length&&(a=e.join("|"),c.Me.Od("chm",a))}this.g8=(a=gvjs_bT(c))?a.toString():null;return c};gvjs_tT.prototype.Eoa=function(){return this.g8};function gvjs_uT(a,b,c,d){b=b.Y(c);(c=d==b)||a.pe("The DataTable column has an unexpected type.  Expected: "+d+", actual: "+b);return c}
var gvjs_qja={annotationColumns:!0,backgroundColor:!0,color:!0,colors:!0,enableEvents:!0,fill:!0,firstHiddenColumn:!0,height:!0,labels:!0,legend:!0,max:!0,min:!0,showCategoryLabels:!0,showValueLabels:!0,singleColumnDisplay:!0,title:!0,width:!0,valueLabelsInterval:!0,chd:!0,chs:!0};function gvjs_vT(a){gvjs_mT.call(this,2,a)}gvjs_m(gvjs_vT,gvjs_mT);function gvjs_wT(a){gvjs_mT.call(this,4,a)}gvjs_m(gvjs_wT,gvjs_mT);function gvjs_xT(a){gvjs_tT.call(this,a)}gvjs_m(gvjs_xT,gvjs_tT);gvjs_xT.prototype.IG=function(a,b){b=b?gvjs_w(b):{};a=a.Rr();a.a_(0,[["",0,0,0,0]]);a.Pp([["",0,0,0,0]]);b.cht="lc";b.color=gvjs_1S;b.colors=[gvjs_1S];b.legend=gvjs_e;var c=b.monochrome?"000000":"",d="1:"+(a.ca()-2),e=b.candlestickWidth;e=typeof e===gvjs_f?String(e):"20";b.chm=["F",c,"0",d,e].join();return gvjs_tT.prototype.IG.call(this,a,b)};function gvjs_yT(a){gvjs_mT.call(this,1,a)}gvjs_m(gvjs_yT,gvjs_mT);function gvjs_zT(a){gvjs_mT.call(this,3,a)}gvjs_m(gvjs_zT,gvjs_mT);function gvjs_AT(a,b){gvjs_O.call(this,a);this.af=new gvjs_In;this.Hr=[];this.mm=[];this.aa=new gvjs_Jq(this);this.G=b||gvjs_rl()}gvjs_m(gvjs_AT,gvjs_O);gvjs_=gvjs_AT.prototype;gvjs_.getSelection=function(){return this.af.getSelection()};gvjs_.setSelection=function(a){var b=this.af.setSelection(a);if(this.container){var c=gvjs_Jn(b.wE,gvjs_Jb);for(a=0;a<c.length;a++)gvjs_BT(this,c[a],gvjs_4S);b=gvjs_Jn(b.vB,gvjs_Jb);for(a=0;a<b.length;a++)gvjs_BT(this,b[a],gvjs_5S)}};
function gvjs_rja(a,b,c){c=c.labelPosition;a.G.Ac(a.container);var d=a.G.K(gvjs_ys,{"class":gvjs_4S}),e=a.G.K(gvjs_zs,{"class":gvjs_4S});a.G.appendChild(a.container,d);a.G.appendChild(d,e);a.Hr=[];a.mm=[];var f=a.G.K(gvjs_Bs,{"class":gvjs_4S});for(d=0;d<b.Z();d++){var g=null,h=gvjs_Nn(a.af,d)?gvjs_5S:gvjs_4S;h=a.G.K(gvjs_As,{"class":h});a.G.appendChild(f,h);a.Hr[d]=h}c==gvjs_dd&&(g=a.G.K(gvjs_Bs,{"class":gvjs_4S}),a.G.appendChild(e,g));a.G.appendChild(e,f);c==gvjs_h&&(g=a.G.K(gvjs_Bs,{"class":gvjs_4S}),
a.G.appendChild(e,g));if(g)for(d=0;d<b.Z();d++)c=a.G.K(gvjs_As,{"class":a.Hr[d].className}),a.G.appendChild(g,c),a.mm[d]=c}
function gvjs_sja(a,b,c){c=c.labelPosition;a.G.Ac(a.container);var d=a.G.K(gvjs_ys,{"class":gvjs_4S}),e=a.G.K(gvjs_zs,{"class":gvjs_4S});a.G.appendChild(a.container,d);a.G.appendChild(d,e);a.Hr=[];a.mm=[];for(d=0;d<b.Z();d++){var f=gvjs_4S;gvjs_Nn(a.af,d)&&(f=gvjs_5S);var g=a.G.K(gvjs_Bs,{"class":f});a.G.appendChild(e,g);var h=a.G.K(gvjs_As,{"class":f});c==gvjs_h?(a.G.appendChild(g,h),f=a.G.K(gvjs_As,{"class":f}),a.G.appendChild(g,f),a.Hr[d]=h,a.mm[d]=f):(c==gvjs_dd&&(f=a.G.K(gvjs_As,{"class":f}),
a.G.appendChild(g,f),a.mm[d]=f),a.G.appendChild(g,h));a.Hr[d]=h}}function gvjs_CT(a,b){for(var c=0;c<b.length;c++){var d=b[c];a.aa.D(d,gvjs_kd,gvjs_q(a.UC,a,c));a.aa.D(d,gvjs_od,gvjs_q(a.mqa,a,c));a.aa.D(d,gvjs_pd,gvjs_q(a.nqa,a,c))}}function gvjs_tja(a,b){for(var c=0;c<a.mm.length;c++)a.G.c3(a.mm[c],b.Ca(c))}
gvjs_.hg=function(a,b,c){var d=c||{},e=0;typeof d.title===gvjs_j&&(d.title=[d.title]);gvjs_6m(new gvjs_7m(this,this.container),gvjs_q(function(){this.VL(b);"h"==d.layout?gvjs_rja(this,b,d):gvjs_sja(this,b,d);var f=d.labelPosition==gvjs_dd||d.labelPosition==gvjs_h,g="h"==d.layout;gvjs_CT(this,this.Hr);f&&(gvjs_tja(this,b),gvjs_CT(this,this.mm));for(var h=this.Hr,k=0;k<h.length;k++){var l=h[k],m=gvjs_w(d),n=gvjs_ZA(this.container,d),p=gvjs__A(this.container,d);g?(n&&(m.width=Math.floor(n/h.length-2)),
p&&(m.height=p-2),f&&(m.height-=this.mm[0].clientHeight)):(p&&(m.height=Math.floor(p/h.length-2)),n&&(m.width=n-2),f&&(m.width-=this.mm[0].clientWidth));m.title=d.title?d.title[k]:null;m.min=d.min?d.min[k]:null;m.max=d.max?d.max[k]:null;m.singleColumnDisplay=k;n=new gvjs_mT(1,l);gvjs_Ym(n,gvjs_Vb,gvjs_q(function(q){gvjs_N(this,gvjs_Vb,q)},this));gvjs_Ym(n,gvjs_g,gvjs_q(function(){e++;e==h.length&&gvjs_N(this,gvjs_g,{})},this));n.draw(b,m);l.firstChild.className="google-visualization-sparkline-image"}},
this))};gvjs_.UC=function(a){a=gvjs_Nn(this.af,a)?null:[{column:a}];this.setSelection(a);gvjs_N(this,gvjs_i,{})};gvjs_.mqa=function(a){gvjs_BT(this,a,gvjs_Nn(this.af,a)?gvjs_5S:gvjs_4S)};gvjs_.nqa=function(a){gvjs_BT(this,a,"google-visualization-sparkline-over")};function gvjs_BT(a,b,c){a.Hr[b].className=c;a.mm[b]&&(a.mm[b].className=c)}gvjs_.VL=function(a){for(var b=a.Z(),c=0;c<b;c++){var d=a.Y(c);if(d!=gvjs_f)throw Error("Invalid type in column "+c+". Expected: number, actual: "+d+".");}};
gvjs_.O=function(){gvjs_J(this.aa);delete this.aa;delete this.Hr;delete this.mm;gvjs_O.prototype.O.call(this)};gvjs_o(gvjs_Bc,gvjs_tT,void 0);gvjs_tT.prototype.getImageUrl=gvjs_tT.prototype.Eoa;gvjs_tT.prototype.draw=gvjs_tT.prototype.draw;gvjs_o(gvjs_yc,gvjs_vT,void 0);gvjs_vT.prototype.draw=gvjs_vT.prototype.draw;gvjs_o(gvjs_zc,gvjs_wT,void 0);gvjs_wT.prototype.draw=gvjs_wT.prototype.draw;gvjs_o(gvjs_Ac,gvjs_xT,void 0);gvjs_xT.prototype.draw=gvjs_xT.prototype.draw;gvjs_o(gvjs_Cc,gvjs_yT,void 0);gvjs_yT.prototype.draw=gvjs_yT.prototype.draw;gvjs_o(gvjs_Dc,gvjs_zT,void 0);gvjs_zT.prototype.draw=gvjs_zT.prototype.draw;
gvjs_o(gvjs_Ec,gvjs_AT,void 0);gvjs_AT.prototype.draw=gvjs_AT.prototype.draw;gvjs_AT.prototype.getSelection=gvjs_AT.prototype.getSelection;gvjs_AT.prototype.setSelection=gvjs_AT.prototype.setSelection;
