/*
 SWFObject v2.2 <http://code.google.com/p/swfobject/> 
 is released under the MIT License <http://www.opensource.org/licenses/mit-license.php> 
*/
var gvjs_FP="SWFObjectExprInst",gvjs_GP="Shockwave Flash",gvjs_HP="application/x-shockwave-flash",gvjs_IP="https://www.gstatic.com/charts/%{package}/%{version}/%{subdir}/%{filename}",gvjs_JP="onreadystatechange";function gvjs_KP(a){return gvjs_Ff(a.format,a.Oh,a.params||{})}
var gvjs_LP=function(){function a(){if(!I){try{var D=x.getElementsByTagName(gvjs_Cb)[0].appendChild(x.createElement(gvjs__w));D.parentNode.removeChild(D)}catch(L){return}I=!0;D=A.length;for(var E=0;E<D;E++)A[E]()}}function b(D){I?D():A[A.length]=D}function c(D){if("undefined"!=typeof w.addEventListener)w.addEventListener("load",D,!1);else if("undefined"!=typeof x.addEventListener)x.addEventListener("load",D,!1);else if("undefined"!=typeof w.attachEvent)q(w,"onload",D);else if(typeof w.onload==gvjs_c){var E=
w.onload;w.onload=function(){E(null);D()}}else w.onload=D}function d(){var D=x.getElementsByTagName(gvjs_Cb)[0],E=x.createElement(gvjs_vd);E.setAttribute(gvjs_Vd,gvjs_HP);var L=D.appendChild(E);if(L){var O=0;(function(){function P(){if("undefined"!=typeof L.GetVariable){var S=L.GetVariable("$version");S&&(S=S.split(" ")[1].split(","),M.nE=[parseInt(S[0],10),parseInt(S[1],10),parseInt(S[2],10)])}else if(10>O){O++;setTimeout(P,10);return}D.removeChild(E);L=null;e()}return P})()()}else e()}function e(){var D=
B.length;if(0<D)for(var E=0;E<D;E++){var L=B[E].id,O=B[E].Wka,P={jF:!1,id:L};if(0<M.nE[0]){var S=p(L);if(S)if(!r(B[E].yxa)||M.yu&&312>M.yu)if(B[E].v9&&g()){P={};P.data=B[E].v9;P.width=S.getAttribute(gvjs_Zd)||"0";P.height=S.getAttribute(gvjs_8c)||"0";S.getAttribute(gvjs_Gb)&&(P.rDa=S.getAttribute(gvjs_Gb));S.getAttribute("align")&&(P.align=S.getAttribute("align"));var T={};S=S.getElementsByTagName("param");for(var ea=S.length,V=0;V<ea;V++)"movie"!=S[V].getAttribute(gvjs_Yv).toLowerCase()&&(T[S[V].getAttribute(gvjs_Yv)]=
S[V].getAttribute(gvjs_Xd));h(P,T,L,O)}else k(S),O&&O(P);else u(L,!0),O&&(P.jF=!0,P.jea=f(L),O(P))}else u(L,!0),O&&((L=f(L))&&"undefined"!=typeof L.SetVariable&&(P.jF=!0,P.jea=L),O(P))}}function f(D){var E=null;(D=p(D))&&D.nodeName==gvjs_4a&&("undefined"!=typeof D.SetVariable?E=D:(D=D.getElementsByTagName(gvjs_vd)[0])&&(E=D));return E}function g(){return!Q&&r("6.0.65")&&(M.ho||M.Kba)&&!(M.yu&&312>M.yu)}function h(D,E,L,O){Q=!0;J=O||null;K={jF:!1,id:L};var P=p(L);if(P){P.nodeName==gvjs_4a?(H=l(P),
G=null):(H=P,G=L);D.id=gvjs_FP;if("undefined"==typeof D.width||!/%$/.test(D.width)&&310>parseInt(D.width,10))D.width="310";if("undefined"==typeof D.height||!/%$/.test(D.height)&&137>parseInt(D.height,10))D.height="137";x.title=x.title.slice(0,47)+" - Flash Player Installation";O=M.An&&M.ho?"ActiveX":"PlugIn";O="MMredirectURL="+w.location.toString().replace(/&/g,"%26")+"&MMplayerType="+O+"&MMdoctitle="+x.title;E.flashVars="undefined"!=typeof E.flashVars?E.flashVars+("&"+O):O;M.An&&M.ho&&4!=P.readyState&&
(O=x.createElement(gvjs_Sb),L+="SWFObjectNew",O.setAttribute(gvjs_9c,L),P.parentNode.insertBefore(O,P),P.style.display=gvjs_e,function(){function S(){4==P.readyState?P.parentNode.removeChild(P):setTimeout(S,10)}return S}()());m(D,E,L)}}function k(D){if(M.An&&M.ho&&4!=D.readyState){var E=x.createElement(gvjs_Sb);D.parentNode.insertBefore(E,D);E.parentNode.replaceChild(l(D),E);D.style.display=gvjs_e;(function(){function L(){4==D.readyState?D.parentNode.removeChild(D):setTimeout(L,10)}return L})()()}else D.parentNode.replaceChild(l(D),
D)}function l(D){var E=x.createElement(gvjs_Sb);if(M.ho&&M.An)E.innerHTML=D.innerHTML;else if(D=D.getElementsByTagName(gvjs_vd)[0])if(D=D.childNodes)for(var L=D.length,O=0;O<L;O++)1==D[O].nodeType&&"PARAM"==D[O].nodeName||8==D[O].nodeType||E.appendChild(D[O].cloneNode(!0));return E}function m(D,E,L){var O=p(L);if(M.yu&&312>M.yu)return ea;if(O)if("undefined"==typeof D.id&&(D.id=L),M.An&&M.ho){var P="";for(S in D)D[S]!=Object.prototype[S]&&(S.toLowerCase()==gvjs_eu?E.movie=D[S]:"styleclass"==S.toLowerCase()?
P+=gvjs_tr+D[S]+'"':"classid"!=S.toLowerCase()&&(P+=" "+S+'="'+D[S]+'"'));var S="";for(var T in E)E[T]!=Object.prototype[T]&&(S+='<param name="'+T+gvjs_yr+E[T]+'" />');O.outerHTML='<object classid="clsid:D27CDB6E-AE6D-11cf-96B8-444553540000"'+P+">"+S+"</object>";F[F.length]=D.id;var ea=p(D.id)}else{T=x.createElement(gvjs_vd);T.setAttribute(gvjs_Vd,gvjs_HP);for(var V in D)D[V]!=Object.prototype[V]&&("styleclass"==V.toLowerCase()?T.setAttribute(gvjs_Gb,D[V]):"classid"!=V.toLowerCase()&&T.setAttribute(V,
D[V]));for(P in E)E[P]!=Object.prototype[P]&&"movie"!=P.toLowerCase()&&(D=T,S=P,V=E[P],L=x.createElement("param"),L.setAttribute(gvjs_Yv,S),L.setAttribute(gvjs_Xd,V),D.appendChild(L));O.parentNode.replaceChild(T,O);ea=T}return ea}function n(D){var E=p(D);E&&E.nodeName==gvjs_4a&&(M.An&&M.ho?(E.style.display=gvjs_e,function(){function L(){if(4==E.readyState){var O=p(D);if(O){for(var P in O)typeof O[P]==gvjs_c&&(O[P]=null);O.parentNode.removeChild(O)}}else setTimeout(L,10)}return L}()()):E.parentNode.removeChild(E))}
function p(D){var E=null;try{E=x.getElementById(D)}catch(L){}return E}function q(D,E,L){D.attachEvent(E,L);C[C.length]=[D,E,L]}function r(D){var E=M.nE;D=D.split(".");D[0]=parseInt(D[0],10);D[1]=parseInt(D[1],10)||0;D[2]=parseInt(D[2],10)||0;return E[0]>D[0]||E[0]==D[0]&&E[1]>D[1]||E[0]==D[0]&&E[1]==D[1]&&E[2]>=D[2]?!0:!1}function t(D,E,L,O){if(!M.An||!M.Kba){var P=x.getElementsByTagName("head")[0];P&&(L=L&&typeof L==gvjs_j?L:gvjs_Fw,O&&(U=N=null),N&&U==L||(O=x.createElement(gvjs_Md),O.setAttribute(gvjs_Vd,
"text/css"),O.setAttribute("media",L),N=P.appendChild(O),M.An&&M.ho&&"undefined"!=typeof x.styleSheets&&0<x.styleSheets.length&&(N=x.styleSheets[x.styleSheets.length-1]),U=L),M.An&&M.ho?N&&typeof N.addRule==gvjs_vd&&N.addRule(D,E):N&&"undefined"!=typeof x.createTextNode&&N.appendChild(x.createTextNode(D+" {"+E+"}")))}}function u(D,E){R&&(E=E?gvjs_Gx:gvjs_Cp,I&&p(D)?p(D).style.visibility=E:t("#"+D,"visibility:"+E,null,null))}function v(D){return null!=/[\\"<>\.;]/.exec(D)&&"undefined"!=typeof encodeURIComponent?
encodeURIComponent(D):D}var w=window,x=document,y=navigator,z=!1,A=[function(){z?d():e()}],B=[],F=[],C=[],H,G,J,K,I=!1,Q=!1,N,U,R=!0,M=function(){var D="undefined"!=typeof x.getElementById&&"undefined"!=typeof x.getElementsByTagName&&"undefined"!=typeof x.createElement,E=y.userAgent.toLowerCase(),L=y.platform.toLowerCase(),O=L?/win/.test(L):/win/.test(E);L=L?/mac/.test(L):/mac/.test(E);E=/webkit/.test(E)?parseFloat(E.replace(/^.*webkit\/(\d+(\.\d+)?).*$/,"$1")):!1;var P=!+"\v1",S=[0,0,0],T=null;if("undefined"!=
typeof y.plugins&&typeof y.plugins[gvjs_GP]==gvjs_vd)!(T=y.plugins[gvjs_GP].description)||"undefined"!=typeof y.mimeTypes&&y.mimeTypes[gvjs_HP]&&!y.mimeTypes[gvjs_HP].enabledPlugin||(z=!0,P=!1,T=T.replace(/^.*\s+(\S+\s+\S+$)/,"$1"),S[0]=parseInt(T.replace(/^(.*)\..*$/,"$1"),10),S[1]=parseInt(T.replace(/^.*\.(.*)\s.*$/,"$1"),10),S[2]=/[a-zA-Z]/.test(T)?parseInt(T.replace(/^.*[a-zA-Z]+(.*)$/,"$1"),10):0);else if("undefined"!=typeof w.ActiveXObject)try{if(T=(new ActiveXObject("ShockwaveFlash.ShockwaveFlash")).GetVariable("$version"))P=
!0,T=T.split(" ")[1].split(","),S=[parseInt(T[0],10),parseInt(T[1],10),parseInt(T[2],10)]}catch(ea){}return{lx:D,nE:S,yu:E,An:P,ho:O,Kba:L}}();(function(){M.lx&&(("undefined"!=typeof x.readyState&&x.readyState==gvjs_Lb||"undefined"==typeof x.readyState&&(x.getElementsByTagName(gvjs_Cb)[0]||x.body))&&a(),I||("undefined"!=typeof x.addEventListener&&x.addEventListener("DOMContentLoaded",a,!1),M.An&&M.ho&&(x.attachEvent(gvjs_JP,function(){function D(){x.readyState==gvjs_Lb&&(x.detachEvent(gvjs_JP,D),
a())}return D}()),w==top&&function(){function D(){if(!I){try{x.documentElement.doScroll(gvjs_dd)}catch(E){setTimeout(D,0);return}a()}}return D}()()),M.yu&&function(){function D(){I||(/loaded|complete/.test(x.readyState)?a():setTimeout(D,0))}return D}()(),c(a)))})();(function(){M.An&&M.ho&&window.attachEvent("onunload",function(){for(var D=C.length,E=0;E<D;E++)C[E][0].detachEvent(C[E][1],C[E][2]);D=F.length;for(E=0;E<D;E++)n(F[E]);for(var L in M)M[L]=null;M=null;for(var O in gvjs_LP)gvjs_LP[O]=null;
gvjs_LP=null})})();return{hDa:function(D,E,L,O){if(M.lx&&D&&E){var P={};P.id=D;P.yxa=E;P.v9=L;P.Wka=O;B[B.length]=P;u(D,!1)}else O&&O({jF:!1,id:D})},BCa:function(D){if(M.lx)return f(D)},b9:function(D,E,L,O,P,S,T,ea,V,oa){var W={jF:!1,id:E};M.lx&&!(M.yu&&312>M.yu)&&D&&E&&L&&O&&P?(u(E,!1),b(function(){L+="";O+="";var ja={};if(V&&typeof V===gvjs_vd)for(var ia in V)ja[ia]=V[ia];ja.data=D;ja.width=L;ja.height=O;ia={};if(ea&&typeof ea===gvjs_vd)for(var Da in ea)ia[Da]=ea[Da];if(T&&typeof T===gvjs_vd)for(var Ea in T)ia.flashVars=
"undefined"!=typeof ia.flashVars?ia.flashVars+("&"+Ea+"="+T[Ea]):Ea+"="+T[Ea];if(r(P))Da=m(ja,ia,E),ja.id==E&&u(E,!0),W.jF=!0,W.jea=Da;else{if(S&&g()){ja.data=S;h(ja,ia,E,oa);return}u(E,!0)}oa&&oa(W)})):oa&&oa(W)},sDa:function(){R=!1},zDa:M,ACa:function(){return{UCa:M.nE[0],YCa:M.nE[1],release:M.nE[2]}},JCa:r,lCa:function(D,E,L){if(M.lx)return m(D,E,L)},pDa:function(D,E,L,O){M.lx&&g()&&h(D,E,L,O)},jDa:function(D){M.lx&&n(D)},kCa:function(D,E,L,O){M.lx&&t(D,E,L,O)},VBa:b,WBa:c,CCa:function(D){var E=
x.location.search||x.location.hash;if(E){/\?/.test(E)&&(E=E.split("?")[1]);if(null==D)return v(E);E=E.split("&");for(var L=0;L<E.length;L++)if(E[L].substring(0,E[L].indexOf("="))==D)return v(E[L].substring(E[L].indexOf("=")+1))}return""},qCa:function(){if(Q){var D=p(gvjs_FP);D&&H&&(D.parentNode.replaceChild(H,D),G&&(u(G,!0),M.An&&M.ho&&(H.style.display=gvjs_Bb)),J&&J(K));Q=!1}}}}();var gvjs_Hia={base:gvjs_uf("https://www.gstatic.com/charts/%{package}/%{version}/"),flash:gvjs_uf("https://www.gstatic.com/charts/%{package}/%{version}/%{filename}"),flash_subdir:gvjs_uf(gvjs_IP),map:gvjs_uf(gvjs_IP)};function gvjs_MP(a,b,c){return{format:gvjs_Hia[a],Oh:{"package":b,version:c}}};
